name: Sanity

on: [push, pull_request]

jobs:

  pychecker:
    name: Check Python Style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check Python Style with >>flack8<<
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8
    - name: Check Python Style with >>black<<
      run: |
        pip install black
        black  --skip-string-normalization --line-length 100 --verbose --check .
